<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * hook_form_Alter() implements.
 */

 function demo1_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
    if($form_id == 'comment_comment_form'){
        //add placeholder subject
        $form['subject']['widget']['0']['value']['#attributes']['placeholder'] = t('Syöta aihe');
        $form['actions']['submit']['#value'] = 'Kommentoi';
    }
    
 }

?>